### ISSUE TITLE
Unable to setup working environment 

### ISSUE THREAD

**Issue by varun1994varun** [tdhintz/tesseract4win64#1]
I want to use the Tesseract dll's which you have provided.
I tried to add the reference in visual studio 2015.
I am able to add Tesseract.dll but the following error pops out when I am trying to add liblept1741.dll and
libtesseract400.dll.
"dll could not be added as reference.Please make sure that the file is accessible,and that is a valid assembly or COM component."
I am totally new to this and I want to use tesseract in c#.
Help me on this.
Thank you

**Comment by tdhintz** [comment]
Reference only tesseract.dll.  The others go in an x64 or x86 folder below the binary. Tesseract.dll loads them itself.

**Comment by varun1994varun** [comment]
**Hi,Thanks for your response.
I have created a new  c# project added Tesseract.dll as reference and placed the other two dll's in bin directory which is the correct path as mentioned ,but still I am getting following error.
It would be great if you help me in setting up tesseract**

Current OS: Windows
Current platform: x64
Custom search path is not defined, skipping.
Checking executing application domain location 'c:\users\ejanthkar varun\documen
ts\visual studio 2015\Projects\demo1netwrappertesseract\bin\x64\Debug' for 'libl
ept1741.dll' on platform x64.
Checking current application domain location 'c:\users\ejanthkar varun\documents
\visual studio 2015\Projects\demo1netwrappertesseract\bin\x64\Debug\' for 'lible
pt1741.dll' on platform x64.
No bin directory exists under the current application domain's location, skippin
g.
Checking working directory 'c:\users\ejanthkar varun\documents\visual studio 201
5\Projects\demo1netwrappertesseract\bin\x64\Debug' for 'liblept1741.dll' on plat
form x64.

Unhandled Exception: System.Reflection.TargetInvocationException: Exception has
been thrown by the target of an invocation. ---> System.DllNotFoundException: Fa
iled to find library "liblept1741.dll" for platform x64.
   at InteropDotNet.LibraryLoader.LoadLibrary(String fileName, String platformNa
me)

**I also tried to build it using the original Tesseract Charlsew project,
Here is what I did.
**I did the changes as you mentioned in your commit link provided. [Commit link](https://github.com/charlesw/tesseract/commit/122585197fce4f25424f5ff7527a38f54a3ee3d1)
I added the liblept1741.dll and libtesseract400.dll to x64 and x86 folder,
I referenced to Tesseract.dll which you provided.
But I am getting following errors-****

->>Metadata file 'C:\Users\Ejanthkar Varun\Desktop\tesseract-4-net wrapper\tesseract-net-charlesw\src\Tesseract\bin\Debug\Net20\Tesseract.dll' could not be found	
Tesseract.Tests

->>Metadata file 'C:\Users\Ejanthkar Varun\Desktop\tesseract-4-net wrapper\tesseract-net-charlesw\src\Tesseract.Tests\bin\Debug\Net20\Tesseract.Tests.dll' could not be found-Tesseract.Tests.Console	

->>'ITessApiSignatures' does not contain a definition for 'BaseAPIDetectOS' and no extension method 'BaseAPIDetectOS' accepting a first argument of type 'ITessApiSignatures' could be found (are you missing a using directive or an assembly reference?)	Tesseract	C:\Users\Ejanthkar Varun\Desktop\tesseract-4-net wrapper\tesseract-net-charlesw\src\Tesseract\Page.cs	

**I know I may be wasting your time but I so desperately want to make it work and I am not able to figure it out.
Thank you.**

**Comment by tdhintz** [comment]
This is a fork of charlesw/tesseract.  You need to ask your questions there.

Place the liblept1741 and libtesseract400 DLLs in the following folder c:\users\ejanthkar varun\documen
ts\visual studio 2015\Projects\demo1netwrappertesseract\bin\x64\Debug\x64.  Notice the extra x64 on the end of that path.

**Comment by varun1994varun** [comment]
Hey,Thanks so much for helping.It's working perfectly now..
