### ISSUE TITLE
Build Successful but not able to reference it!

### ISSUE THREAD

**Issue by srinivas1994** [tdhintz/tesseract4win64#3]
Hi,First of all thank you so much for providing instructions on how to build dll for tesseract 4.0 version.
I followed the steps as you mentioned-

**git clone https://github.com/tesseract-ocr/tesseract tesseract
cd tesseract
cppan  (I assume this wasn't necessary, but I'm trying to avoid improvising)
mkdir Win64 && cd Win64
cppan ..
cmake .. -G "Visual Studio 15 2017 Win64"
 edit cppan.yml and uncomment, and edit, this line:
#generator: Visual Studio 14 2015 Win64 -> generator: Visual Studio 15 2017 Win64
cppan --generate .
Open the tesseract.sln created in this same folder using Visual Studio 2017, select the Release configuration and then build.**

I was successfully able to build it with no errors.
But I want to generate the tesseract.dll file which can be used  in a c# project.
So,I went to properties of tesseract project and changed the configuration type and target extension to **.dll**
I successfully generated tesseract.dll file.
But I am not able to reference this generated tesseract.dll in a c# project.
When I am trying to do add reference following error is shown-
**A reference to tesseract.dll could not be added.Please make sure it is a valid assembly or COM component.**

The dll which you have provided I am perfectly able to use it and add as a reference to a c# project.
I would like to build tesseract dll's by myself and use it.
Can you please help me on how to generate tesseract.dll which can be referenced by a c# project.

I am sorry I know that you don't maintain the tesseract.net project but I wasted so many hours on figuring out how it should be done but of no use.
Thank you,Have a great day!

**Comment by tdhintz** [comment]
Don't reference tesseract-ocr directly.  That project should create a dll that it places in a Win64\bin folder.  It should already be a dll.  The tesseract.net project is c# managed code that manually loads the dll created by tesseract-ocr.  It expects that dll to be placed in an x64 folder BELOW your executable, and it wants it named a certain name.  It ALSO needs leptonica so you need to find or build Dan Bloomberg's version of that.  Place it with your Tesseract-Ocr dll.  Again, you'll need to give leptonica a special name.

**Comment by srinivas1994** [comment]
Thanks for your reply.
I will build the leptonica and place both tesseract and leptonica dll under x64 folder of tesseract.net project and see if I am able to use it.
Cheers :)

**Comment by srinivas1994** [comment]
Hi @tdhintz , I have updated the names in the Constants.cs file.
I have changed the files as it is mentioned in [here](https://github.com/charlesw/tesseract/commit/122585197fce4f25424f5ff7527a38f54a3ee3d1).
But when I build I still get errors searching for old liblept172.dll and libtesseract304.dll
and also it says cannot find metadata for Tesseract.dll and Tesseract.Tests.dll.
Please help me on this.
Thank you.
