### ISSUE TITLE
Can anyone give in step by step tutorial for building Tesseract4.0

### ISSUE THREAD

**Issue by amitbsconcept** [tdhintz/tesseract4win64#8]
Hi to all experts. I am sorry i am a very novice person in the world of DotNet. I tried to understand in as how to build in the libtesseract 4.0 and all. But unfortunately i was not able to compile it 100%. Even if i was able to run through a build (as described), i failed in producing libtesseract

I always was able to generate Tesseract.dll - and the same was not sufficient for me to be able to load the same in my application.

Actually we are building in a Python based application and i was able to build and use the library sucessfully in Linux environment. The same was trying to achieve in Windows environment but still am a novice on the same. Please can anyone guide me as how once can build the same from scratch on windows using the source to generate (as we see in generated dll files in this repository).

**Comment by tdhintz** [comment]
Those instructions are found in the tesseract-ocr project page on GitHub.

**Comment by amitbsconcept** [comment]
I did follow the instructions...
Let me share you the steps i followed up:
1. Install CPPAN / Cmake
2. git clone https://github.com/tesseract-ocr/tesseract tesseract
3.  mkdir Win64 && cd Win64
4. cppan ..
5. cmake .. -G "Visual Studio 15 2017 Win64" -DCPPAN_USE_CACHE=0 (this was useful step to actually allow the proper compilation for me.
6. Updated the CPPAN and uncommented on the generator string
7. cppan --generate .. - generated the solution files.
8. Opened up in Visual Studio - selected the release version
8.1 - Set the openmp feature (Disabled for myself)
9. Built the version.

I do get the EXE / DLL file - but what i got was tesseract dll (probably required for the main executable) but i was not able to build in libtesseract.dll 
I was not able to able to genera the libtesseract.dll - the same that i see as output generated in this following GIT. 

With this given lib file - i could also have loaded up in python and execute barebone stuff - not all - just barebone - but atleast it ran through. But with the ones built with the compilation from visual studio - i was not able to build things that i could load up in my python application.

It will be great if you guys can help me build up stuff - where i failed - what can i do to get it right.

Thanking you in advance.

**Comment by tdhintz** [comment]
When you say you can’t build libtesseract.dll, do you mean that you had compilation errors or do you mean that no dll was created by the name libtesseract.dll.

What were the errors?

**Comment by amitbsconcept** [comment]
There was no dll created by the name libtesseract.dll

There were warnings but no error.

**Comment by tdhintz** [comment]
Open …\Win64\tesseract.sln with Visual Studio.

Select Solution Explorer tab.

Right click libtesseract from the tree (the project) and choose Properties.

Under General | Target Name note the name of the dll that will be created and the Output Directory.  Look for the Target Name file in the Output Directory in your filesystem.

**Comment by amitbsconcept** [comment]
Well thank you for the help.. the issue is resolved. The DLL that was getting generated was surely tesseract4.dll and not libtesseract400.dll 

I was having issues loading the same but finally with God's grace it got cracked up correctly and now am able to commence back to the project.
